version: '3.3'
services:
  docker-hexchat:
    #build: .
    build:
      context: hc
    hostname: docker-hexchat
    #restart: unless-stopped
    volumes:
      - hexchatvol:/home/signal-user
      - $XAUTHORITY:$XAUTHORITY
      - /tmp/.X11-unix:/tmp/.X11-unix:rw 
      - /etc/localtime:/etc/localtime:rw
      - ./hc/Downloads:/home/signal-user/Downloads/:rw
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY
    devices:
      - "/dev/snd"
    image: innovanon/docker-hexchat:latest
    container_name: docker-hexchat
    links:
      - "inspircd-docker:inspircd-docker"

  inspircd-docker:
    #build: https://github.com/inspircd/inspircd.git
    image: inspircd/inspircd-docker:latest
    container_name: inspircd-docker
    hostname: inspircd-docker
    #command: --redis-host redis
    #links:
    #  - "hexchat:hexchat"
    #  - "iroffer:iroffer"
    ports:
      - "6697:6697"
    restart: unless-stopped

  iroffer:
    image: innovanon/iroffer:latest
    container_name: iroffer
    build:
      context: iroffer
      #dockerfile: Dockerfile-iroffer
    hostname: iroffer
    restart: unless-stopped
    volumes:
      - ./iroffer/downloads:/home/signal-user/downloads/:rw
      - ./iroffer/uploads:/home/signal-user/uploads/:rw
        #- ./cron.log:/var/log/cron.log:rw
      - cronlog:/var/log:rw
    links:
      - "inspircd-docker:inspircd-docker"

# TODO needs stunnel
#  rss2irc:
#    image: innovanon/rss2irc:latest
#    container_name: rss2irc
#    build:
#      context: rss2irc
#    environment:
#      - FEEDURL=https://innovanon-inc.github.io/feed.xml
#      - PORT=6697
#      - CHANNEL=#InnovAnon
#      - NICK=rss2irc
#      - OPTIONS=--ident=InnovAnon-Inc --link
#      - DELAY=10
#    hostname: rss2irc
#    restart: unless-stopped
#    links:
#      - "inspircd-docker:inspircd-docker"

  shbot:
    image: innovanon/shbot:latest
    container_name: shbot
    build:
      context: shbot
    #environment:
    hostname: shbot
    restart: unless-stopped
    links:
      - "inspircd-docker:inspircd-docker"

volumes:
  hexchatvol:
  cronlog:

