version: '3.3'
services:
  hexchat:
    #build: .
    build:
      context: hc
    hostname: hexchat
    #restart: unless-stopped
    volumes:
      - hexchatvol:/home/signal-user
      - $XAUTHORITY:$XAUTHORITY
      - /tmp/.X11-unix:/tmp/.X11-unix:rw 
      - /etc/localtime:/etc/localtime:rw
      - ./hc/Downloads:/home/signal-user/Downloads/:rw
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY
    devices:
      - "/dev/snd"
    image: innovanon/docker-hexchat:latest
    container_name: docker-hexchat

  inspircd-docker:
    #build: https://github.com/inspircd/inspircd.git
    image: inspircd/inspircd-docker
    container_name: inspircd-docker
    hostname: inspircd
    #command: --redis-host redis
    links:
      - "hexchat:hexchat"
      - "iroffer:iroffer"
    ports:
      - "6697:6697"
    restart: unless-stopped

  iroffer:
    image: innovanon/iroffer:latest
    container_name: iroffer
    build:
      context: iroffer
      #dockerfile: Dockerfile-iroffer
    hostname: iroffer
    restart: unless-stopped
    volumes:
      - ./iroffer/downloads:/home/signal-user/downloads/:rw
      - ./iroffer/uploads:/home/signal-user/uploads/:rw
      #- ./cron.log:/var/log/cron.log:rw
      - cronlog:/var/log:rw

volumes:
  hexchatvol:
  cronlog:

